### ISSUE TITLE
Building with Visual Studio 2015

### ISSUE THREAD

**Issue by rickrice** [flirc/sdk#1]
I created a VS 2015 C++ console app and included ...\sdk-master\libs\Win\libflirc.dll. When I built the project there is an error saying libflirc.dll is invalid or corrupt. Dumpbin was able to read the dll however. How can I get VS to read the file?

**Comment by jdk** [comment]
Visual studio isn't supported. Only mingw on windows or in a mingw cross compiler.

**Comment by R-Klimkeit** [comment]
Visual studio is not directly supported, but you should go fine using the SDK's DLLs "libflirc.dll" and "libir.dll" with any .NET-Application. You just have to declare the correct PINVOKEs ...

I had to do so to implement the function of "irtools.exe listen" into a Visual-Basic-Project.

You might want to take a look at these .NET-Code-Snippets: https://github.com/flirc/sdk/issues/7#issuecomment-2813157571

Hope this helps :-)
