### ISSUE TITLE
semver.h missing from version control

### ISSUE THREAD

**Issue by rickrice** [flirc/sdk#3]
semver.h is called out on line 21 of version_history.h and is not under version control.

**Comment by jdk** [comment]
just wanted to let you know I'm trying to get another release out and address these issues. Thank you so much.

**Comment by rickrice** [comment]
I went to order some PIR-1’s and your store is out of stock on everything. When will they be available?

Sent from my iPhone

On Apr 11, 2018, at 10:05 PM, Jason Kotzin <notifications@github.com<mailto:notifications@github.com>> wrote:


just wanted to let you know I'm trying to get another release out and address these issues. Thank you so much.

**Comment by jdk** [comment]
PIR-1s?

**Comment by rickrice** [comment]
Yes

Sent from my iPhone

On Apr 12, 2018, at 10:47 AM, Jason Kotzin <notifications@github.com<mailto:notifications@github.com>> wrote:


PIR-1s?

**Comment by jdk** [comment]
Sorry, I don't have any products with that code, can you be more specific?

**Comment by rickrice** [comment]
This is the product:

https://www.promixis.com/pir-1.php



On Apr 12, 2018, at 12:03 PM, Jason Kotzin <notifications@github.com<mailto:notifications@github.com>> wrote:


Sorry, I don't have any products with that code, can you be more specific?

**Comment by jdk** [comment]
ha, what the hell is that? That's not my product....

https://flirc.tv/more/flirc-usb

My SDK wont work with that product. Holy shit, and that thing is 60 bucks, you've got to be kidding me....

**Comment by jdk** [comment]
you can shoot me a message over my website, I'll send you one of my products. Consider it a thank you for the help with the SDK.

**Comment by rickrice** [comment]
I appreciate that but I don’t know your website. I got to you through support from the site I sent you the link for.

Sent from my iPhone

On Apr 12, 2018, at 11:36 PM, Jason Kotzin <notifications@github.com<mailto:notifications@github.com>> wrote:


you can shoot me a message over my website, I'll send you one of my products. Consider it a thank you for the help with the SDK.

**Comment by rickrice** [comment]
Ok, just saw this email with your site. I don’t know how we got hooked up but I’m glad because I originally brought a Flirc and couldn’t get it to transmit IR. Can you help me with that? Please send your regular email, I won’t spam you or share it.

Sent from my iPhone

On Apr 12, 2018, at 9:10 PM, Jason Kotzin <notifications@github.com<mailto:notifications@github.com>> wrote:


ha, what the hell is that? That's not my product....

https://flirc.tv/more/flirc-usb

My SDK wont work with that product. Holy shit, and that thing is 60 bucks, you've got to be kidding me....

**Comment by rickrice** [comment]
I got to the code I sent the bug report for through the Promixis site and somehow ended up in contact with you. Will that code work with the Flirc because it’s different from what’s on the Flirc site.

Sent from my iPhone

On Apr 12, 2018, at 9:10 PM, Jason Kotzin <notifications@github.com<mailto:notifications@github.com>> wrote:


ha, what the hell is that? That's not my product....

https://flirc.tv/more/flirc-usb

My SDK wont work with that product. Holy shit, and that thing is 60 bucks, you've got to be kidding me....

**Comment by jdk** [comment]
> I got to the code I sent the bug report for through the Promixis

This is really concerning, any chance you can share this?

If you go to http://www.flirc.tv/contact, you can submit a message through the contact form. It goes directly to me, I can't post it on here because of robots.

**Comment by rickrice** [comment]
Yes, tonight or tomorrow I’ll be in contact with you.

Sent from my iPhone

On Apr 13, 2018, at 8:12 AM, Jason Kotzin <notifications@github.com<mailto:notifications@github.com>> wrote:


I got to the code I sent the bug report for through the Promixis

This is really concerning, any chance you can share this?

If you go to http://www.flirc.tv/contact, you can submit a message through the contact form. It goes directly to me, I can't post it on here because of robots.

**Comment by jdk** [comment]
fixed with f12b61b81e0d94f1fb816392f4f50bb9429e258a
