### ISSUE TITLE
Add support for Linux_aarch64

### ISSUE THREAD

**Issue by dreerr** [flirc/sdk#6]
I'm trying to compile flirc_util for my NVIDIA Jetson Nano, which is on arm64. Unfortunately there is no library file for this architecture. Would you please supply the library file or give instructions on how to build it?

**Comment by mingwandroid** [comment]
I believe we'll have to reverse engineer this. Shame they sell the product, and claim it to have an SDK when it doesn't.

**Comment by EvTheFuture** [comment]
Same here but Pi with aarch64

**Comment by mingwandroid** [comment]
I believe we may need to reverse engineer the lib. Shame flirc claims to be pro open source when they release binary only libraries.

**Comment by andreshs** [comment]
Please! I need pi with aarch64 as well!
Can either the library be open source or provide a build for aarch64?
